# Generated by Django 3.2.8 on 2022-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='blink',
            field=models.CharField(default='F', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='fireball',
            field=models.CharField(default='Q', max_length=10),
        ),
    ]
