# Generated by Django 3.2.8 on 2022-04-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20220425_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='blink',
            field=models.CharField(blank=True, default='F', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fireball',
            field=models.CharField(blank=True, default='Q', max_length=10, null=True),
        ),
    ]
