# Generated by Django 3.2.8 on 2022-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20220425_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='blink',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fireball',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
