# Generated by Django 3.2.8 on 2022-04-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20220425_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='blink',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fireball',
        ),
    ]
