# Generated by Django 3.2.8 on 2022-04-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20220425_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='blink',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='fireball',
            field=models.IntegerField(default=''),
        ),
    ]
