# Generated by Django 3.2.8 on 2022-04-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20220426_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='blink',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='player',
            name='fireball',
            field=models.IntegerField(default=81),
        ),
    ]
