# Generated by Django 3.2.8 on 2022-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20220426_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.URLField(blank=True, max_length=510),
        ),
    ]
